### ISSUE TITLE
App unexpectedly closes when attempting to move cards in the game

### ISSUE THREAD

**Issue by gbarkerz** [gbarkerz/AccessibleSolitaire#25]
Periodically the app simply closes down mid-move. This was the output when once occurred under the debugger.

[0:] Tapped on card: Empty Dealt card pile
[0:] DealtCard AccessibleName: Empty Dealt card pile
[0:] DealtCard AccessibleName: Queen of Diamonds, selected, 1 of 1
[0:] DealtCard AccessibleName: Queen of Diamonds, selected, 1 of 1
[0:] DealtCard AccessibleName: Queen of Diamonds, selected, 1 of 1
[0:] DealtCard AccessibleName: 10 of Diamonds, 4 of 4
[0:] DealtCard AccessibleName: 10 of Diamonds, 4 of 4
[0:] DealtCard AccessibleName: Queen of Diamonds
[0:] DealtCard AccessibleName: Queen of Diamonds, 1 of 6
[0:] DealtCard AccessibleName: Jack of Clubs, 2 of 6
[0:] DealtCard AccessibleName: Jack of Clubs, 2 of 6
[0:] DealtCard AccessibleName: Jack of Clubs, 2 of 6
[0:] DealtCard AccessibleName: Jack of Clubs, 2 of 6
[0:] DealtCard AccessibleName: 10 of Hearts, 3 of 6
[0:] DealtCard AccessibleName: 10 of Hearts, 3 of 6
[0:] DealtCard AccessibleName: 10 of Hearts, 3 of 6
[0:] DealtCard AccessibleName: 10 of Hearts, 3 of 6
[0:] DealtCard AccessibleName: 9 of Spades, 4 of 6
[0:] DealtCard AccessibleName: 9 of Spades, 4 of 6
[0:] DealtCard AccessibleName: 9 of Spades, 4 of 6
[0:] DealtCard AccessibleName: 9 of Spades, 4 of 6
[0:] DealtCard AccessibleName: 8 of Diamonds, 5 of 6
[0:] DealtCard AccessibleName: 8 of Diamonds, 5 of 6
[0:] DealtCard AccessibleName: 8 of Diamonds, 5 of 6
[0:] DealtCard AccessibleName: 8 of Diamonds, 5 of 6
[0:] DealtCard AccessibleName: 7 of Clubs, 6 of 6
[0:] DealtCard AccessibleName: 7 of Clubs, 6 of 6
[0:] DealtCard AccessibleName: 7 of Clubs, 6 of 6
[0:] DealtCard AccessibleName: 7 of Clubs, 6 of 6
[GestureDetector] handleMessage TAP
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[GestureDetector] obtain mCurrentDownEvent. id: 514239507 caller: mono.android.view.View_OnTouchListenerImplementor.n_onTouch:-2 mono.android.view.View_OnTouchListenerImplementor.onTouch:31 android.view.View.dispatchTouchEvent:16221 
[GestureDetector] obtain mCurrentMotionEventRaw. action: 2 id: 791657754
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[WindowOnBackDispatcher] OnBackInvokedCallback is not enabled for the application.
[WindowOnBackDispatcher] Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ssiblesolitaire] Explicit concurrent mark compact GC freed 520KB AllocSpace bytes, 0(0B) LOS objects, 49% free, 7660KB/14MB, paused 181us,1.947ms total 19.384ms
[WindowOnBackDispatcher] OnBackInvokedCallback is not enabled for the application.
[WindowOnBackDispatcher] Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
[Choreographer] Skipped 45 frames!  The application may be doing too much work on its main thread.
[InputMethodManager] invalidateInput
[InputMethodManager] invalidateInput
[InputMethodManager] invalidateInput
[InputMethodManager] invalidateInput
[InputMethodManager] invalidateInput
[InputMethodManager] invalidateInput
[InputMethodManager] invalidateInput
[InputMethodManager] invalidateInput
[InputMethodManager] invalidateInput
[InputMethodManager] invalidateInput
[InputMethodManager] invalidateInput
[InputMethodManager] invalidateInput
[InputMethodManager] invalidateInput
[InputMethodManager] invalidateInput
[InputMethodManager] invalidateInput
[InputMethodManager] invalidateInput
[ResourcesCompat] Failed to inflate ColorStateList, leaving it to the framework
[ResourcesCompat] java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f040117 a=-1}, theme={InheritanceMap=[id=0x7f120157a11y.gbarker.accessiblesolitaire:style/Maui.MainTheme.NoActionBar, id=0x7f120156a11y.gbarker.accessiblesolitaire:style/Maui.MainTheme, id=0x7f12026ea11y.gbarker.accessiblesolitaire:style/Theme.MaterialComponents.DayNight, id=0x7f120287a11y.gbarker.accessiblesolitaire:style/Theme.MaterialComponents.Light, id=0x7f12006ba11y.gbarker.accessiblesolitaire:style/Base.Theme.MaterialComponents.Light, id=0x7f1200a4a11y.gbarker.accessiblesolitaire:style/Base.V21.Theme.MaterialComponents.Light, id=0x7f120092a11y.gbarker.accessiblesolitaire:style/Base.V14.Theme.MaterialComponents.Light, id=0x7f120093a11y.gbarker.accessiblesolitaire:style/Base.V14.Theme.MaterialComponents.Light.Bridge, id=0x7f120160a11y.gbarker.accessiblesolitaire:style/Platform.MaterialComponents.Light, id=0x7f120241a11y.gbarker.accessiblesolitaire:style/Theme.AppCompat.Light, id=0x7f120053a11y.gbarker.accessiblesolitaire:style/Base.Theme.AppCompat.Light, id=0x7f1200b6a11y.gbarker.accessiblesolitaire:style/Base.V28.Theme.AppCompat.Light, id=0x7f1200b3a11y.gbarker.accessiblesolitaire:style/Base.V26.Theme.AppCompat.Light, id=0x7f1200ada11y.gbarker.accessiblesolitaire:style/Base.V23.Theme.AppCompat.Light, id=0x7f1200aba11y.gbarker.accessiblesolitaire:style/Base.V22.Theme.AppCompat.Light, id=0x7f1200a0a11y.gbarker.accessiblesolitaire:style/Base.V21.Theme.AppCompat.Light, id=0x7f1200b9a11y.gbarker.accessiblesolitaire:style/Base.V7.Theme.AppCompat.Light, id=0x7f12015da11y.gbarker.accessiblesolitaire:style/Platform.AppCompat.Light, id=0x7f120168a11y.gbarker.accessiblesolitaire:style/Platform.V25.AppCompat.Light, id=0x1030241android:style/Theme.Material.Light.NoActionBar, id=0x1030237android:style/Theme.Material.Light, id=0x103000candroid:style/Theme.Light, id=0x1030005android:style/Theme], Themes=[a11y.gbarker.accessiblesolitaire:style/Maui.MainTheme.NoActionBar, forced, a11y.gbarker.accessiblesolitaire:style/Maui.SplashTheme, forced, a11y.gbarker.accessiblesolitaire:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
[ResourcesCompat] 	at android.content.res.TypedArray.getColor(TypedArray.java:529)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.inflate(ColorStateListInflaterCompat.java:160)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXmlInner(ColorStateListInflaterCompat.java:125)
[ResourcesCompat] 	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXml(ColorStateListInflaterCompat.java:104)
[ResourcesCompat] 	at androidx.core.content.res.ResourcesCompat.inflateColorStateList(ResourcesCompat.java:262)
[ResourcesCompat] 	at androidx.core.content.res.ResourcesCompat.getColorStateList(ResourcesCompat.java:236)
[ResourcesCompat] 	at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:558)
[ResourcesCompat] 	at androidx.appcompat.content.res.AppCompatResources.getColorStateList(AppCompatResources.java:48)
[ResourcesCompat] 	at androidx.appcompat.widget.TintTypedArray.getColorStateList(TintTypedArray.java:179)
[ResourcesCompat] 	at androidx.appcompat.widget.AppCompatCompoundButtonHelper.loadFromAttributes(AppCompatCompoundButtonHelper.java:81)
[ResourcesCompat] 	at androidx.appcompat.widget.AppCompatCheckBox.<init>(AppCompatCheckBox.java:84)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:231)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:227)
[ResourcesCompat] 	at com.google.android.material.checkbox.MaterialCheckBox.<init>(MaterialCheckBox.java:223)
[ResourcesCompat] 	at crc6452ffdc5b34af3a0f.ScopedFragment.n_onCreateView(Native Method)
[ResourcesCompat] 	at crc6452ffdc5b34af3a0f.ScopedFragment.onCreateView(ScopedFragment.java:49)
[ResourcesCompat] 	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3114)
[ResourcesCompat] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:557)
[ResourcesCompat] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1845)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3042)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2945)
[ResourcesCompat] 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)
[ResourcesCompat] 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
[ResourcesCompat] 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
[ResourcesCompat] 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
[ResourcesCompat] 	at android.os.Handler.handleCallback(Handler.java:958)
[ResourcesCompat] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[ResourcesCompat] 	at android.os.Looper.loopOnce(Looper.java:230)
[ResourcesCompat] 	at android.os.Looper.loop(Looper.java:319)
[ResourcesCompat] 	at android.app.ActivityThread.main(ActivityThread.java:8919)
[ResourcesCompat] 	at java.lang.reflect.Method.invoke(Native Method)
[ResourcesCompat] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
[ResourcesCompat] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
[MaterialButton] MaterialButton manages its own background to control elevation, shape, color and states. Consider using backgroundTint, shapeAppearance and other attributes where available. A custom background will ignore these attributes and you should consider handling interaction states such as pressed, focused and disabled
[Choreographer] Skipped 37 frames!  The application may be doing too much work on its main thread.
Thread started: <Thread Pool> #6
Thread started: <Thread Pool> #7
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 0
[ViewRootImpl@b26ccc7[MainActivity]] ViewPostIme pointer 1
[ssiblesolitaire] NativeAlloc concurrent mark compact GC freed 64KB AllocSpace bytes, 0(0B) LOS objects, 49% free, 8415KB/16MB, paused 191us,8.708ms total 80.485ms
[Choreographer] Skipped 211 frames!  The application may be doing too much work on its main thread.
[WindowOnBackDispatcher] OnBackInvokedCallback is not enabled for the application.
[WindowOnBackDispatcher] Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
[OpenGLRenderer] Davey! duration=4460ms; Flags=0, FrameTimelineVsyncId=17390503, IntendedVsync=198512986521260, Vsync=198515339442184, InputEventId=0, HandleInputStart=198515344857662, AnimationStart=198515344859162, PerformTraversalsStart=198515391880277, DrawStart=198515485812200, FrameDeadline=198512997632371, FrameInterval=198515342992969, FrameStartTime=11151284, SyncQueued=198515510338700, SyncStart=198515510593008, IssueDrawCommandsStart=198515512874777, SwapBuffers=198517432737199, FrameCompleted=198517447129237, DequeueBufferDuration=15500, QueueBufferDuration=2316885, GpuCompleted=198517439430930, SwapBuffersCompleted=198517447129237, DisplayPresentTime=198510789649819, CommandSubmissionCompleted=198517432737199,

**Comment by gbarkerz** [comment]
This is fixed in V1.15.

The crash occurred fairly regularly when moving long sets of cards between dealt card piles, or adding a card from the upturned card pile to the end of a dealt card pile, but no useful debug info was ever provided. The crash seemed to be avoided by not having the dealt card CollectionViews contained in a vertically-scrollable ScrollView. Perhaps MAUI/Android couldn't handle both the ScrollView and a contained CollectionView trying to figure out at the same time how to react to a scroll becoming possible. So to avoid the crash, the ScrollView was changed to be horizontally-scrollable only. That means it can scroll horizontally when the app's Zoom Level is greater than 100%. Now that the ScrollView does not scroll vertically (and its height is fixed), to access cards in a dealt card pile which are out of view, each individual CollectionView can be scrolled vertically. Having each CollectionView scroll vertically individually is perhaps a better user experience anyway, relative to only being able to scroll all the dealt card piles as one set.
